const words = [
    'makan',
    'coding',
    'belajar',
    'masak',
    'kuku kaki',
    'kakek',
    'astaga',
    'tidur',
    'seratus ribu',
    'menyeberang jalan',
    'minum whiskey',
    'memancing perkara',
    'melompati sawah',
    'berendam',
    'menendang terompet',
    'mencela rakyat',
    'melatih pesut etam',
    'menemukan baju dalam John Tarkpor Sonkaliey',
    'mencengangkan',
    'melambaikan tangan kanan aparatur pemerintah',
    'buaya, biawak, buaian',
    'sempat-sempatnya semut-semut itu saling senyum-senyum dan salam-salaman',
    'keledai makan kedelai di kedai',
    'engkau ulung guling ulang ulas suling',
    'kuaci, kacang, kecoa, kuaci, kacang, kecoa',
    'kelapa diparut, kepala digaruk, kelapa diparut, kepala digaruk, kelapa diparut, kepala digaruk',
    'ular lari lurus',
    'kakaktua kakak kakekku kenal kakaktua kakak kakekmu',
    'jangan coba-coba cium cucu-cucuku kalau cuma mau cium cucu-cucuku cuma-cuma',
    'tiba-tiba, si botak batuk-batuk di atas batu bata',
    'Olinga Atangana',
    'Emalue Serge',
    'Pierre Njanka',
    'Redouane Barkaoui',
    'Mbida Messi',
    'Greg Nwokolo',
    'Miro Baldo Bento',
    'Christian Lenglolo',
    'Keith Kayamba Gumbs',
    'Roger Batoum'
]

module.exports = words